# Generated by Django 5.1.4 on 2024-12-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=50),
        ),
    ]
